
language: ruby
rvm:
  - 2.2.2

before_install:
  - sudo apt-get update
  - sudo apt-get install golang

install:
  - bundle install

script:
  - echo "Hello, World!"

after_success:
  - ./scripts/atlas.sh